Superheroes.UI/Controllers/Superheroes_VilliansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Superheroes.DATA;

namespace Superheroes.UI.Controllers
{   
    [Authorize(Roles = "Admin, Superheroes")]
    public class Superheroes_VilliansController : Controller
    {
        private SuperheroesEntities db = new SuperheroesEntities();

        // GET: Superheroes_Villians
        public ActionResult Index()
        {
            var superheroes_Villians = db.Superheroes_Villians.Include(s => s.Alignment);
            return View(superheroes_Villians.ToList());
        }
        
        // GET: Superheroes_Villians/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Superheroes_Villians superheroes_Villians = db.Superheroes_Villians.Find(id);
            if (superheroes_Villians == null)
            {
                return HttpNotFound();
            }
            return View(superheroes_Villians);
        }
        [Authorize(Roles = "Admin")]
        // GET: Superheroes_Villians/Create
        public ActionResult Create()
        {
            ViewBag.AlignmentID = new SelectList(db.Alignments, "AlignmentID", "AlignmentType");
            return View();
        }

       
        // POST: Superheroes_Villians/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "HeroID,HeroName,Alias,Origin,AlignmentID")] Superheroes_Villians superheroes_Villians)
        {
            if (ModelState.IsValid)
            {
                db.Superheroes_Villians.Add(superheroes_Villians);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AlignmentID = new SelectList(db.Alignments, "AlignmentID", "AlignmentType", superheroes_Villians.AlignmentID);
            return View(superheroes_Villians);
        }

        // GET: Superheroes_Villians/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Superheroes_Villians superheroes_Villians = db.Superheroes_Villians.Find(id);
            if (superheroes_Villians == null)
            {
                return HttpNotFound();
            }
            ViewBag.AlignmentID = new SelectList(db.Alignments, "AlignmentID", "AlignmentType", superheroes_Villians.AlignmentID);
            return View(superheroes_Villians);
        }


        // POST: Superheroes_Villians/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "HeroID,HeroName,Alias,Origin,AlignmentID")] Superheroes_Villians superheroes_Villians)
        {
            if (ModelState.IsValid)
            {
                db.Entry(superheroes_Villians).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AlignmentID = new SelectList(db.Alignments, "AlignmentID", "AlignmentType", superheroes_Villians.AlignmentID);
            return View(superheroes_Villians);
        }

        // GET: Superheroes_Villians/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Superheroes_Villians superheroes_Villians = db.Superheroes_Villians.Find(id);
            if (superheroes_Villians == null)
            {
                return HttpNotFound();
            }
            return View(superheroes_Villians);
        }

        // POST: Superheroes_Villians/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Superheroes_Villians superheroes_Villians = db.Superheroes_Villians.Find(id);
            db.Superheroes_Villians.Remove(superheroes_Villians);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        
       
    }
}

Superheroes.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title | SH, Inc.</title>
    <link rel="shortcut icon" type="image/x-icon" href="~/favicon .ico" />
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500italic,500,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <!-- Bootstrap -->
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet">
    <!-- FontAwesome -->
    <link href="~/Content/css/font-awesome.min.css" rel="stylesheet" />

    <!-- MaterialCSS -->
    <link rel="stylesheet" href="~/Content/css/material.min.css">
    <!-- RipplesCSS -->
    <link rel="stylesheet" href="~/Content/css/ripples.min.css">


    <!-- ThemeCSS & Responsive CSS -->
    <link rel="stylesheet" href="~/Content/css/style.css">
    <link rel="stylesheet" href="~/Content/css/responsive.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link rel="icon" type="image/x-icon" href="favicon.ico5520">
</head>

<body>
    <header class="header">
        <div data-velocity="-.4" id="particles" class="header-bg"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="social-links">
                        <a class="btn social-link" id="facebook" href="javascript:void(0)"><i class="fa fa-facebook"></i> <div class="ripple-wrapper"></div></a>
                        <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-twitter"></i> <div class="ripple-wrapper"></div></a>
                        <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-google-plus"></i> <div class="ripple-wrapper"></div></a>
                        <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-youtube"></i> <div class="ripple-wrapper"></div></a>
                        <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-linkedin"></i> <div class="ripple-wrapper"></div></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="site-title-table">
            <div class="site-title-tablecell">
                <div class="slide-text">
                    <h2><a href="index.html"><span>S</span>uper <span>H</span>eroes, <span>I</span>nc.</a></h2>
                    <p class="tagline">Lowering crime rates through education, training, and protection</p>
                </div>
            </div>
        </div>
    </header>
    <section class="maincontent-wrap">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="maincotnent shadow-z-1">
                        
                        <div class="mainmenu">
                            <div class="navbar navbar-nobg">
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                        <span class="sr-only">Toggle navigation</span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                </div>
                                <div class="navbar-collapse collapse">
                                    <ul class="nav navbar-nav">
                                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                                        <li>@Html.ActionLink("Our Mission", "About", "Home")</li>
                                        <li>@Html.ActionLink("Programs", "Activities", "Home")</li>

                                        @if (User.IsInRole("Admin") || User.IsInRole("Superheroes"))
                                        {
                                            <li>@Html.ActionLink("Superheroes", "Index", "Superheroes_Villians")</li>
                                        }

                                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                                    </ul>
                                </div>
                                    
                                    @*<li class="active"><a href="index.html">Home <div class="ripple-wrapper"></div></a></li>
            <li><a href="about.html">About</a></li>
            <li><a href="archive.html">Local Activities</a></li>
            <li><a href="contact.html">Contact</a></li>
            <li><a href="archive.html">Travel</a></li>
            <li><a href="single.html">Single</a></li>
            <li><a href="contact.html">Contact</a></li>*@

                               

                            </div>
                            <div class="admin">
                                <ul>
                                    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
            {

                                        <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
                                        <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
                                    }


                                    @Html.Partial("_LoginPartial")
                                </ul>
                            </div>
                        </div>
                        <div class="container body-content">
                            @RenderBody()
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>








  
    @RenderSection("scripts", required: false)

    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-md-6 col-lg-offset-1">
                    <div class="footer-wid">
                        <h2 class="wid-title">@*A*@<span>@*vengers*@</span></h2>
                        <p>
                            @*Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis
                                nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan,*@
                        </p>
                    </div>
                </div>
                <div class="col-lg-5 col-md-6">
                    <div class="footer-wid">
                        <h2 class="wid-title">@*Newsletter*@</h2>
                        <p>@*Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.*@</p>

                        <div class="newsletter-form">
                            <form action="index.html">
                                <input class="shadow-z-1" type="email" placeholder="Your Email address">
                                <button type="submit" class="btn btn-material-red">Subscribe Now!</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="footer-bottom">
                        <div class="row">
                            <div class="col-md-8">
                                <div class="copyright-text">
                                    <p>© 2015 Avengers - All Rights Reserved. Coded with <i class="fa fa-heart"></i> by <a href="http://wpexpand.com" target="_blank">WP Expand</a></p>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="social-links footer-social-links">
                                    <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-facebook"></i> <div class="ripple-wrapper"></div></a>
                                    <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-twitter"></i> <div class="ripple-wrapper"></div></a>
                                    <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-google-plus"></i> <div class="ripple-wrapper"></div></a>
                                    <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-youtube"></i> <div class="ripple-wrapper"></div></a>
                                    <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-linkedin"></i> <div class="ripple-wrapper"></div></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="~/Content/js/vendor/jquery-1.11.2.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="~/Content/js/bootstrap.min.js"></script>
        <script src="~/Content/js/material.min.js"></script>
        <script src="~/Content/js/@*@*@*ripple*@*@*@s.min.js"></script>
        <script src="~/Content/js/jquery.scrolly.js"></script>
        <script src="~/Content/js/jquery.particleground.min.js"></script>
        <script src="~/Content/js/main.js"></script>
</body>
</html>











































@*<!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - My ASP.NET Application</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                        @if (Request.IsAuthenticated && User.IsInRole("Admin")) {
                            <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
                            <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
                        }
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
    </html>*@